#!/bin/bash

cd /app/src

export GO111MODULE=on

# Copy HEAD test files from /tests (overwrites BASE state)
mkdir -p "."
cp "/tests/command_test.go" "command_test.go"

# Run only tests from command_test.go using -run regex pattern to exclude unrelated test files
go test -v -run '^Test(SingleCommand|ChildCommand|CallCommandWithoutSubcommands|RootExecuteUnknownCommand|SubcommandExecuteC|ExecuteContext|ExecuteContextC|Execute_NoContext|RootUnknownCommandSilenced|CommandAlias|EnablePrefixMatching|AliasPrefixMatching|ChildSameName|GrandChildSameName|FlagLong|FlagShort|ChildFlag|ChildFlagWithParentLocalFlag|FlagInvalidInput|FlagBeforeCommand|StripFlags|DisableFlagParsing|PersistentFlagsOnSameCommand|EmptyInputs|ChildFlagShadowsParentPersistentFlag|PersistentFlagsOnChild|RequiredFlags|PersistentRequiredFlags|PersistentRequiredFlagsWithDisableFlagParsing|InitHelpFlagMergesFlags|HelpCommandExecuted|HelpCommandExecutedOnChild|HelpCommandExecutedOnChildWithFlagThatShadowsParentFlag|SetHelpCommand|HelpFlagExecuted|HelpFlagExecutedOnChild|HelpFlagInHelp|FlagsInUsage|HelpCommandExecutedOnNonRunnableChild|HelpExecutedOnNonRunnableChild|VersionFlagExecuted|VersionFlagExecutedWithNoName|ShortAndLongVersionFlagInHelp|LongVersionFlagOnlyInHelpWhenShortPredefined|ShorthandVersionFlagExecuted|VersionTemplate|ShorthandVersionTemplate|RootErrPrefixExecutedOnSubcommand|RootAndSubErrPrefix|VersionFlagExecutedOnSubcommand|ShorthandVersionFlagExecutedOnSubcommand|VersionFlagOnlyAddedToRoot|ShortVersionFlagOnlyAddedToRoot|VersionFlagOnlyExistsIfVersionNonEmpty|ShorthandVersionFlagOnlyExistsIfVersionNonEmpty|ShorthandVersionFlagOnlyAddedIfShorthandNotDefined|ShorthandVersionFlagOnlyAddedIfVersionNotDefined|UsageIsNotPrintedTwice|VisitParents|Suggestions|CaseInsensitive|CaseSensitivityBackwardCompatibility|RemoveCommand|ReplaceCommandWithRemove|DeprecatedCommand|Hooks|PersistentHooks|GlobalNormFuncPropagation|NormPassedOnLocal|NormPassedOnInherited|ConsistentNormalizedName|FlagOnPflagCommandLine|HiddenCommandExecutes|HiddenCommandIsHidden|CommandsAreSorted|EnableCommandSortingIsDisabled|UsageWithGroup|UsageHelpGroup|UsageCompletionGroup|UngroupedCommand|AddGroup|WrongGroupFirstLevel|WrongGroupNestedLevel|WrongGroupForHelp|WrongGroupForCompletion|SetOutput|SetOut|SetErr|SetIn|UsageStringRedirected|CommandPrintRedirection|FlagErrorFunc|FlagErrorFuncHelp|SortedFlags|MergeCommandLineToFlags|UseDeprecatedFlags|TraverseWithParentFlags|TraverseNoParentFlags|TraverseWithBadParentFlags|TraverseWithBadChildFlag|TraverseWithTwoSubcommands|UpdateName|CalledAs|FParseErrWhitelistBackwardCompatibility|FParseErrWhitelistSameCommand|FParseErrWhitelistParentCommand|FParseErrWhitelistChildCommand|FParseErrWhitelistSiblingCommand|SetContext|SetContextPreRun|SetContextPreRunOverwrite|SetContextPersistentPreRun|NoRootRunCommandExecutedWithVersionSet|NoRootRunCommandExecutedWithoutVersionSet|HelpCommandExecutedWithVersionSet|HelpCommandExecutedWithoutVersionSet|HelpflagCommandExecutedWithVersionSet|HelpflagCommandExecutedWithoutVersionSet|Find|UnknownFlagShouldReturnSameErrorRegardlessOfArgPosition)$' .
test_status=$?

if [ $test_status -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
exit "$test_status"
