#!/bin/bash

cd /app/src

export GO111MODULE=on

# Copy HEAD test files from /tests (overwrites BASE state)
mkdir -p "."
cp "/tests/command_test.go" "command_test.go"

# Run all tests from command_test.go
# We run tests at the current directory (.) which is the main package
go test -v -run '^(TestSingleCommand|TestChildCommand|TestCallCommandWithoutSubcommands|TestRootExecuteUnknownCommand|TestSubcommandExecuteC|TestExecuteContext|TestExecuteContextC|TestExecute_NoContext|TestRootUnknownCommandSilenced|TestCommandAlias|TestEnablePrefixMatching|TestAliasPrefixMatching|TestChildSameName|TestGrandChildSameName|TestFlagLong|TestFlagShort|TestChildFlag|TestChildFlagWithParentLocalFlag|TestFlagInvalidInput|TestFlagBeforeCommand|TestStripFlags|TestDisableFlagParsing|TestPersistentFlagsOnSameCommand|TestEmptyInputs|TestChildFlagShadowsParentPersistentFlag|TestPersistentFlagsOnChild|TestRequiredFlags|TestPersistentRequiredFlags|TestPersistentRequiredFlagsWithDisableFlagParsing|TestInitHelpFlagMergesFlags|TestHelpCommandExecuted|TestHelpCommandExecutedOnChild|TestHelpCommandExecutedOnChildWithFlagThatShadowsParentFlag|TestSetHelpCommand|TestHelpFlagExecuted|TestHelpFlagExecutedOnChild|TestHelpFlagInHelp|TestFlagsInUsage|TestHelpExecutedOnNonRunnableChild|TestVersionFlagExecuted|TestVersionFlagExecutedWithNoName|TestShortAndLongVersionFlagInHelp|TestLongVersionFlagOnlyInHelpWhenShortPredefined|TestShorthandVersionFlagExecuted|TestVersionTemplate|TestShorthandVersionTemplate|TestVersionFlagExecutedOnSubcommand|TestShorthandVersionFlagExecutedOnSubcommand|TestVersionFlagOnlyAddedToRoot|TestShortVersionFlagOnlyAddedToRoot|TestVersionFlagOnlyExistsIfVersionNonEmpty|TestShorthandVersionFlagOnlyExistsIfVersionNonEmpty|TestShorthandVersionFlagOnlyAddedIfShorthandNotDefined|TestShorthandVersionFlagOnlyAddedIfVersionNotDefined|TestUsageIsNotPrintedTwice|TestVisitParents|TestSuggestions|TestCaseInsensitive|TestCaseSensitivityBackwardCompatibility|TestRemoveCommand|TestReplaceCommandWithRemove|TestDeprecatedCommand|TestHooks|TestPersistentHooks|TestGlobalNormFuncPropagation|TestNormPassedOnLocal|TestNormPassedOnInherited|TestConsistentNormalizedName|TestFlagOnPflagCommandLine|TestHiddenCommandExecutes|TestHiddenCommandIsHidden|TestCommandsAreSorted|TestEnableCommandSortingIsDisabled|TestUsageWithGroup|TestUsageHelpGroup|TestUsageCompletionGroup|TestUngroupedCommand|TestAddGroup|TestWrongGroupFirstLevel|TestWrongGroupNestedLevel|TestWrongGroupForHelp|TestWrongGroupForCompletion|TestSetOutput|TestSetOut|TestSetErr|TestSetIn|TestUsageStringRedirected|TestCommandPrintRedirection|TestFlagErrorFunc|TestFlagErrorFuncHelp|TestSortedFlags|TestMergeCommandLineToFlags|TestUseDeprecatedFlags|TestTraverseWithParentFlags|TestTraverseNoParentFlags|TestTraverseWithBadParentFlags|TestTraverseWithBadChildFlag|TestTraverseWithTwoSubcommands|TestUpdateName|TestCalledAs|TestFParseErrWhitelistBackwardCompatibility|TestFParseErrWhitelistSameCommand|TestFParseErrWhitelistParentCommand|TestFParseErrWhitelistChildCommand|TestFParseErrWhitelistSiblingCommand|TestSetContext|TestSetContextPreRun|TestSetContextPreRunOverwrite|TestSetContextPersistentPreRun|TestNoRootRunCommandExecutedWithVersionSet|TestNoRootRunCommandExecutedWithoutVersionSet|TestHelpCommandExecutedWithVersionSet|TestHelpCommandExecutedWithoutVersionSet|TestHelpflagCommandExecutedWithVersionSet|TestHelpflagCommandExecutedWithoutVersionSet)$' .
test_status=$?

if [ $test_status -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
exit "$test_status"
